### PR TITLE
Changed C1.CENTER to BorderLayout.CENTER for component constraint.  T…

### PR DESCRIPTION
**Pull request by shannah**
…hey aren't the same

### CODE REVIEW

**Comment by codenameone** [comment]
https://github.com/codenameone/CodenameOne/blob/master/CodenameOne/src/com/codename1/ui/layouts/BorderLayout.java#L176-L197

**Comment by shannah** [comment]
But `Container.addComponent(int, Component)` is already defined, and interprets the `int` parameter as an index, and not a constraint.

**Comment by codenameone** [comment]
Shit. I might have to rethink that... Maybe a special case.

**Comment by codenameone** [comment]
Looking at this again with fresh eyes there is an addComponent(int, Component) but there is no add(int, Component) so the first statement should work... The second shouldn't. The solution is to just change addComponent to add

**Pull request closed without merging**
